variable "flavor" { default = "m1.large" }
variable "image" { default = "Rocky 9.3" }
variable "name1" { default = "Project-123456789" } # replace 123456789 with your student number
variable "name2" { default = "Jenkins-123456789" } # replace 123456789 with your student number
variable "keypair" { default = "cloud" } # do not change this for any reason
variable "pool" { default = "cscloud_private_floating" }
variable "server1_script" { default = "./project.sh" }
variable "server2_script" { default = "./jenkins.sh" }
variable "security_description" { default = "Terraform security group" }
variable "security_name" { default = "Terraform-123456789" } # replace 123456789 with your student number