// import type { Metadata } from "next";
// import { Inter} from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";
// import Layout from "@/components/Layout";
// import Footer from "@/components/Footer";

// const inter = Inter({subsets: ["latin"]})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className="h-full">
//       <body
//         className={cn(
//           "relative h-full font-sans antialiased",
//           inter.className
//         )}
//       >
//         <Layout>{children}</Layout>
//         <Footer/>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Layout from "@/components/Layout"; // Your custom Layout
import QueryProvider from "@/components/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alacrity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "relative h-full font-sans antialiased",
          inter.className
        )}
      >
        <QueryProvider>
        <Layout>{children}</Layout>
        </QueryProvider>
      </body>
    </html>
  );
}